<?php  if (!defined('BASEPATH')) exit('No direct script access allowed');
$lang['presentacion_titulo']='Nuestra Empresa<span> / Presentaci&oacute;n </span>';
$lang['presentacion_texto']='<div class="subtitulos">
<h4>Una larga y productiva historia</h4>
</div>
<p>Laboratorios CELSIUS S.A., un &iacute;cono uruguayo en su rubro de actividad, nace en abril de 1936, dedic&aacute;ndose desde sus mismos inicios a la elaboraci&oacute;n y venta de especialidades m&eacute;dicas.<br />En 1996 adquiere la prestigiosa firma Dermur Cosm&eacute;ticos, incursionando en esta actividad con el mismo rigor empleado en las especialidades farmac&eacute;uticas. Complementando otros aspectos vinculados al &aacute;rea de la salud humana, inaugura en mayo del 2003 DiagnosticA Celsius, importando y distribuyendo productos e insumos destinados al laboratorio de an&aacute;lisis cl&iacute;nico. Calidad, servicio, vanguardia tecnol&oacute;gica y una firme pol&iacute;tica de apostar a los recursos humanos han pautado su trayectoria.</p>
<h4>Una constante apuesta al desarrollo</h4>
<p>La planta industrial, es por derecho propio un cap&iacute;tulo trascendente en el desarrollo nacional en materia de especialidades farmac&eacute;uticas y cosm&eacute;ticas, estando certificada y validada por t&eacute;cnicos de la Uni&oacute;n Europea, hecho que coloc&oacute; a Laboratorios CELSIUS una generaci&oacute;n tecnol&oacute;gica por delante de la normativa actual del MERCOSUR y, por lo tanto, en excelentes condiciones para penetrar en los mercados vecinos.</p>
<p>Adem&aacute;s de la fabricaci&oacute;n de especialidades farmac&eacute;uticas y cosm&eacute;ticas,  en CELSIUS se realizan estudios de biodisponibilidad y bioequivalencia de nuevas formulaciones farmac&eacute;uticas en coordinaci&oacute;n con el Departamento de Desarrollo de Productos.</p>
<h4>La calidad</h4>
<p>Laboratorios CELSIUS ha mantenido la calidad de sus productos,  como uno de los pilares de su gesti&oacute;n. Por ello ha buscado mantener su departamento de Control de Calidad dotado de especialistas en el &aacute;rea y equipado con tecnolog&iacute;a de an&aacute;lisis de &uacute;ltima generaci&oacute;n.</p>
<p>En CELSIUS estamos compenetrados con la idea de construcci&oacute;n de la calidad, en la selecci&oacute;n de los proveedores de las materias primas e insumos, en el dise&ntilde;o de los procedimientos de trabajo durante los procesos de elaboraci&oacute;n y en las diferentes etapas de an&aacute;lisis. Pero este concepto de calidad no se termina luego de culminado el proceso de elaboraci&oacute;n. Cada unidad vendida es seguida y registrada de forma de poder ser rastreada si la situaci&oacute;n lo requiere.</p>
<div class="subtitulos">
<h4>Un distintivo constante de CELSIUS ha sido la atenci&oacute;n al cuerpo m&eacute;dico, distribuidores y p&uacute;blico en general.</h4>
</div>
<p>Laboratorios CELSIUS ha seleccionado con igual cuidado sus socios internacionales,  proveedores de las distintas tecnolog&iacute;as de diagn&oacute;stico, considerando s&oacute;lo aquellos que cumplen con normas de calidad internacionales (FDA, CE y OMS).  En todos los casos se realizan estudios de validaci&oacute;n locales con la participaci&oacute;n de reconocidos laboratorios estatales.</p>
<h4>Un futuro firme</h4>
<p>Manteniendo las cualidades que lo caracterizan, Laboratorios CELSIUS se enfrenta a la consolidaci&oacute;n de su posici&oacute;n en el mercado interno y a su proyecci&oacute;n internacional.</p>';
$lang['presentacion_texto1']='espa&ntilde;ol';
$lang['infraestructura_titulo']='Nuestra Empresa<span> / Infraestructura</span>';
$lang['infraestructura_texto']='<p>Laboratorios CELSIUS cuenta en Montevideo con una importante planta elaboradora. En ella se fabrican, con los m&aacute;s altos est&aacute;ndares de calidad, diversas formas farmac&eacute;uticas est&eacute;riles y no est&eacute;riles, entre las que se encuentran inyectables l&iacute;quidos, comprimidos, c&aacute;psulas, polvos, jarabes, gotas, suspensiones, supositorios vaginales, cremas, ung&uuml;entos y geles, as&iacute; como la exclusiva l&iacute;nea de cosmec&eacute;uticos DERMUR. Se producen en  la actualidad aproximadamente 10.000.000 de unidades al a&ntilde;o que se destinan tanto al mercado local  como a la exportaci&oacute;n.</p>
<p>CELSIUS emplea unas 270 personas incluyendo a personal de f&aacute;brica, administrativo, comercial, laboratorios y desarrollo, de las cuales un importante porcentaje importante son profesionales universitarios. Es pol&iacute;tica de la empresa realizar programas peri&oacute;dicos de capacitaci&oacute;n y actualizaci&oacute;n. En todo momento se siguen procedimientos normalizados y documentados, de acuerdo con las Buenas Pr&aacute;cticas de Manufactura (G.M.P.) de productos farmac&eacute;uticos. Se utiliza adem&aacute;s, un importante parque de maquinaria en permanente renovaci&oacute;n.</p>
<p>La planta cuenta con un sistema de acondicionamiento, purificaci&oacute;n y renovaci&oacute;n de aire que permite alcanzar, en sus distintos sectores, &aacute;reas con clases de aire 10,000 y 100,000, requeridas para la fabricaci&oacute;n de los diversos productos. Adem&aacute;s, un sistema de generaci&oacute;n y control de presiones diferenciales entre los espacios comunes y las salas de fabricaci&oacute;n, as&iacute; como entre los diferentes sectores de la planta, garantiza en todo momento las condiciones &oacute;ptimas para evitar para evitar la contaminaci&oacute;n cruzada.</p>
<p>Se dispone adem&aacute;s de un sistema de generaci&oacute;n de agua desmineralizada a partir de agua corriente potable, para la fabricaci&oacute;n de todas las formas farmac&eacute;uticas no est&eacute;riles. A su vez, esta agua desmineralizada alimenta un sistema de destilaci&oacute;n que genera agua destilada para la elaboraci&oacute;n de las especialidades inyectables.</p>
<p>CELSIUS ha comenzado una nueva etapa de expansi&oacute;n  con la adquisici&oacute;n del laboratorio GENA  S.A. en Ecuador e inaugurando nuevas oficinas y laboratorio para su Divisi&oacute;n ATGen &ndash;Diagn&oacute;stica en el predio del LATU.</p>';
$lang['mercados_titulo']='Nuestra Empresa<span> / Mercados</span>';
$lang['mercados_texto']='<p>CELSIUS se encuentra presente en una gran variedad de mercados dentro de Uruguay y en el exterior.</p>
<div class="subtitulos">
<h4>En Uruguay</h4>
</div>
<p>CELSIUS es activo proveedor del Estado Uruguayo a trav&eacute;s de las licitaciones p&uacute;blicas del pa&iacute;s. Sus productos hospitalarios son reconocidos tanto por sus marcas como por su calidad. Tambi&eacute;n se encuentra presente en el Mercado Mutual (Sistema de Cobertura de Salud Privado) el cual cubre a la mayor&iacute;a de los uruguayos. En este mercado CELSIUS es gran proveedor de las principales instituciones en las cuales tambi&eacute;n realiza la promoci&oacute;n activa de sus productos. Es pol&iacute;tica de la empresa dar apoyo a los profesionales de la salud para optimizar el uso de sus productos.</p>
<p>CELSIUS posee una amplia cobertura del padr&oacute;n de m&eacute;dicos uruguayos mediante dos equipos de visitadores m&eacute;dicos altamente capacitados por nuestro departamento de asesor&iacute;a m&eacute;dica.</p>
<p>En el Mercado Farmac&eacute;utico Minorista tiene importante presencia, con un cuerpo de vendedores dedicados a atender personalmente a las farmacias, sin intermediarios, lo que brinda la oportunidad de trabajar en forma muy cercana con las personas que tienen contacto directo con el consumidor final.</p>
<p>La empresa tambi&eacute;n realiza  Fabricaci&oacute;n para Terceros, contando entre sus clientes con reconocidas empresas multinacionales, as&iacute; como gran cantidad de laboratorios regionales y locales. Todas estas empresas conf&iacute;an en los altos est&aacute;ndares de calidad de Celsius para la producci&oacute;n, ya sea de parte o incluso la totalidad de sus especialidades.</p>
<p>Forma parte de los Objetivos Estrat&eacute;gicos de la empresa brindar apoyo a actividades de investigaci&oacute;n cient&iacute;fica, contando al presente con convenios de colaboraci&oacute;n con centros de estudios del pa&iacute;s.</p>
<div class="subtitulos">
<h4>En el Exterior</h4>
</div>
<p>CELSIUS realiza exportaciones con regularidad desde hace a&ntilde;os al Caribe as&iacute; como a otros pa&iacute;ses. de Sudam&eacute;rica. Luego de un per&iacute;odo de gran crecimiento dentro de Uruguay, CELSIUS se encuentra abocado en la actualidad a la apertura de nuevos mercados en el exterior. Las caracter&iacute;sticas de la empresa como su tama&ntilde;o y experiencia, le dan los atributos necesarios para poder ofrecer sus productos de l&iacute;nea,  desarrollos a medida y fabricaci&oacute;n para terceros sin importar el mercado de destino.</p>';
$lang['recursoshumanos_titulo']='Nuestra Empresa<span> / Recursos Humanos</span>';
$lang['recursoshumanos_texto']='<p>Nuestra inserci&oacute;n en la cadena de la salud nos hace  que seamos particularmente cuidadosos y rigurosos en nuestras acciones.</p>
<p>En un mercado cada vez m&aacute;s competitivo, en CELSIUS consideramos que las personas que trabajan aqu&iacute; son parte de los componentes estrat&eacute;gicos y diferenciales de nuestra empresa. La calidad de su trabajo, su entusiasmo y compromiso, la satisfacci&oacute;n en sus tareas y la consideraci&oacute;n de que el trato que reciben es justo, influye de manera importante en la productividad, en la reputaci&oacute;n de nuestra empresa y, en definitiva, en nuestra proyecci&oacute;n de futuro.</p>
<p>Para Recursos Humanos su gran desaf&iacute;o es implementar programas que sean positivos tanto para las personas como para la empresa. Las buenas pr&aacute;cticas de Recursos Humanos son importantes si generan valor a ambos. Este es nuestro compromiso y nuestra raz&oacute;n de ser en cada acci&oacute;n o programa que realizamos.</p>
<p>Si Ud. quiere postularse para integrar el equipo de trabajo de CELSIUS. <a href="/trabajar_lab.php">Ingrese su CV</a> en este mismo sitio.</p>
<p>De esta forma incorporaremos sus datos personales a nuestra base de datos de postulantes.</p>
<p>La informaci&oacute;n proporcionada por Ud. ser&aacute; utilizada con total confidencialidad.</p>';
$lang['salonconferencias_texto_mapa']='<p class="salon_conferencias">Plano de Ubicaci&oacute;n. Laboratorios Celsius - Sal&oacute;n de Conferencias.</br>
      Oficinas y Planta Industrial: Av. Joaqu&iacute;n Su&aacute;rez 3593.</br>Sal&oacute;n de Conferencias: Valdense 3624.</p>
      <iframe width="780" height="450" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com.uy/maps?f=q&amp;source=s_q&amp;hl=es&amp;geocode=&amp;q=3624+Valdense,+Montevideo,+Departamento+de+Montevideo&amp;aq=0&amp;oq=Valdense+3624&amp;sll=-34.805964,-56.214563&amp;sspn=0.376617,0.694885&amp;ie=UTF8&amp;hq=&amp;hnear=Valdense,+Montevideo,+Departamento+de+Montevideo&amp;t=m&amp;z=14&amp;ll=-34.864433,-56.197188&amp;output=embed"></iframe>
      <br /><small><a href="https://maps.google.com.uy/maps?f=q&amp;source=embed&amp;hl=es&amp;geocode=&amp;q=3624+Valdense,+Montevideo,+Departamento+de+Montevideo&amp;aq=0&amp;oq=Valdense+3624&amp;sll=-34.805964,-56.214563&amp;sspn=0.376617,0.694885&amp;ie=UTF8&amp;hq=&amp;hnear=Valdense,+Montevideo,+Departamento+de+Montevideo&amp;t=m&amp;z=14&amp;ll=-34.864433,-56.197188" style="color:#004594;text-align:left">Ver mapa más grande</a></small>';
$lang['salonconferencias_texto']='<div class="img_salon">&nbsp;&nbsp; <img title="conferencias.jpg" src="http://celsius.framework/assets/cache/assets/uploads/jfilebrowser/conferencias/95x95_3/conferencias.jpg" alt="" width="95" height="95" /> <img title="conferencias.jpg" src="http://celsius.framework/assets/cache/assets/uploads/jfilebrowser/conferencias/95x95_3/conferencias.jpg" alt="" width="95" height="95" /></div>';
/* End of file empresa_lang.php */