<?php  if (!defined('BASEPATH')) exit('No direct script access allowed');
$lang['investigacion_titulo'] = 'investigación';
$lang['investigacion_proyectos_titulo'] = 'proyectos en marcha';
$lang['investigacion_tesis_titulo'] = 'tesis de postgrado';
$lang['investigacion_facilidades_titulo'] = 'facilidades';
$lang['investigacion_texto'] = '<p>El área de trabajo que abordamos se enfoca en el agua como recurso estratégico y la ecología de los ecosistemas acuáticos: sistemas límnicos (ríos, arroyos, lagunas y embalses) y marinos costeros (estuarios, plataforma marina interna). Nuestro principal objetivo es el análisis de la estructura y función de los ecosistemas acuáticos, la identificación de patrones en la ocurrencia y abundancia de los organismos en un amplio rango de escalas, y el estudio de los procesos generadores y/ o modificadores de dichos patrones y funciones. </p>
				<p>Un elemento central de nuestro trabajo lo constituye el análisis de la relación entre las actividades humanas y la estructura y funciones ecosistémicas. Es decir, la investigación de los impactos que las modificaciones introducidas por la intervención humana ejercen sobre diferentes aspectos de los ecosistemas, y en particular sobre la capacidad de éstos para mantener sus funciones y permitir su uso racional en el largo plazo. Esta línea se basa en un fuerte componente experimental complementado con enfoques observacionales, teóricos y de modelación.</p>
				<p>La línea general descrita resulta de la interacción coordinada de actividades entre quiénes integramos el grupo de investigadores; representamos escuelas con tradiciones y perspectivas diversas que convergen en el interés por el estudio de los patrones y funciones en ecosistemas acuáticos, y cuya actividad profesional está en gran medida motivada por la preocupación de problemas concretos resultantes de la interacción entre el Hombre y la Naturaleza.</p>';
$lang['investigacion_ver_listado'] = 'ver investigaciones';
$lang['proyecto_ver_mas'] = 'ver más >';
$lang['tesis_descargar'] = 'descargar resumen';

$lang['investigacion_facilidades_texto'] = '<p>Nuestras actividades de investigación y docencia se realizan principalmente en el Centro Universitario de la Región Este, en el Instituto de Investigaciones Biológicas Clemente Estable (Laboratorios de Etología Ecología y Evolución y de Microbiología) y en la Facultad de Ciencias (Secciones Limnología y Oceanografía-Ecología Marina). </p>																																																																																										
        <p>Provisoriamente gran parte de los trabajos experimentales se realizan en laboratorios del CURE emplazados en el predio de PROBIDES (Programa de Conservación de la Biodiversidad y Desarrollo Sustentable en los Humedales del Este), próximo a la ciudad de Rocha. En 2014 contaremos con laboratorios ubicados en el nuevo edificio del CURE – Sede Rocha.</p>
        <p>Algunos de los laboratorios con los que contamos: Laboratorio Biología Molecular, Laboratorio de cultivos organismos acuáticos y Laboratorio de Microscopía. Dichos laboratorios están equipados con diversos equipos nuevos y de vanguardia con los que realizamos investigaciones en áreas tales como la ecología y fisiología de organismos acuáticos, biología molecular y calidad de agua. Este equipamiento ha sido financiado a través de programas de apoyo de la Universidad de la República, de PEDECIBA Biología y Geociencias, y programas internacionales como Marie Curie y Max Planc Institute</p>';

$lang['investigacion_facilidades_texto_imagenes'] = 'Laboratorios del CURE ubicados en PROBIDES';
$lang['investigacion_facilidades_laboratorios_titulos'] = 'Para conocer sobre nuestro laborotarios se puede ingresar en los siguientes items:';
