<?php  if (!defined('BASEPATH')) exit('No direct script access allowed');
$lang['historia_titulo']='Historia';
$lang['historia_sub_titulo']='Somos una empresa con m&aacute;s de 40 a&ntilde;os de actividad ininterrumpida en plaza.';
$lang['historia_columna_izquierda']='<p>Es en el a&ntilde;o 1966 que los Hnos. Carlos y H&eacute;ctor Gallo deciden comprar una peque&ntilde;a auque a&ntilde;osa empresa familiar llamada Cafaro Hnos. fundada en el a&ntilde;o 1933, situada en el barrio del Cord&oacute;n en Montevideo Uruguay. Esta empresa se dedicaba a los Arenados y Metalizados en planta con un perfil netamente artesanal</p>
<p>Es del principal rubro que los Hnos. Gallo toman el nombre que dar&aacute; inicio a nuestra empresa METALIZADORA URUGUAYA S.A que hoy cuenta con m&aacute;s de 45 a&ntilde;os de trayectoria.</p>
<p>Si bien en los primeros a&ntilde;os mantuvieron el perfil artesanal de los trabajos estos fueron incursionando y transformando la empresa en una pujante herramienta industrial .</p>
<p>Es as&iacute; que pocos a&ntilde;os mas tarde comienzan los trabajos en el exterior de sus talleres realizando tratamientos en tanques para firmas como  Fabrica Nacional de Cerveza y para la firma CIR S.A. una de las principales sider&uacute;rgica del pa&iacute;s.</p>
<p>A partir de ah&iacute; con pujanza e inventiva se fue ampliando la cartera de clientes industriales, logrando aproximadamente por el a&ntilde;o 1970 que la industria frigor&iacute;fica y mas aun que los compradores extranjeros avalen el metalizado como una alternativa sanitaria al acero inoxidable permitiendo tratar in situ estructuras imposibles de desmontar.</p>
<p><img title="historia1.jpg" src="../../../../assets/cache/assets/uploads/jfilebrowser/historia/300x160_3/historia1.jpg" alt="Historia" width="300" height="160" /></p>
<img src="../../../../assets/images/historia1.jpg" alt="" /> <img src="../../../../assets/images/historia2.jpg" alt="" />';
$lang['historia_columna_centro']='<p>Esta actividad que contribuyo a que nuestro pa&iacute;s fuera lo que hoy es en materia de exportaci&oacute;n de carnes, le creo un gran desafi&oacute; a nuestra empresa debido fundamentalmente a la estacionalidad de la actividad y la gran cantidad de frigor&iacute;ficos que requer&iacute;an nuestros servicios (Carrasco, Canelones, Tacuaremb&oacute;, La Caballada, Codadesa, Santos Lugares, entre muchos otros que podemos recordar) esto nos obligaba a la importaci&oacute;n de equipamiento, el cual quedaba ocioso buena parte del tiempo.</p>
<p>Es as&iacute; que luego de un viaje que uno de los fundadores realizara a Europa observara que en esos momentos se estaban restaurando en Paris monumentos y edificios hist&oacute;ricos, con equipos similares a los nuestros, si bien con t&eacute;cnicas y abrasivos diferentes.</p>
<p>Una vez arribado se plantea la oportunidad, se generan los contactos con empresas del exterior para aprender las t&eacute;cnicas y se realizan las modificaciones a los equipos ya existentes generando que  nuestra empresa se convierte en la pionera y principal empresa de restauraci&oacute;n edilicia, realiz&aacute;ndose las principales obras nacionales tanto publicas como privadas.</p>
<p>La historia no termina all&iacute;, m&aacute;s trabajo y m&aacute;s y mejor equipamiento, mas capacitaci&oacute;n e inversi&oacute;n  nos obligaron a ir siempre hacia delante.</p>
<img  25px;" src="../../../../assets/images/historia3.jpg" alt="" />
<p>Se incorporaron a nuestro trabajo nuevas &aacute;reas como la naval y la petroqu&iacute;mica, logrando aqu&iacute; tambi&eacute;n posicionarnos cono la mayor empresa nacional en la preparaci&oacute;n de superficies y aplicaci&oacute;n de pinturas en grandes superficies y estructuras como sin duda lo son los Barcos y los Tanques de Combustible, brind&aacute;ndole servicio al dique Regusci y Voulminot en un comienzo que posteriormente fuera adquirido</p>';
$lang['historia_columna_derecha']='<img  15px;" src="../../../../assets/images/historia4.jpg" alt="" /> <img src="../../../../assets/images/historia5.jpg" alt="" />
<p>por el grupo Tsakos Industrias Navales y a la Armada Nacional en todos sus diques y barcos a flote como tambi&eacute;n en la industria petroqu&iacute;mica siendo la empresa ANCAP uno de nuestros principales clientes.</p>
<p>La incorporaci&oacute;n de tecnolog&iacute;as, productos y m&eacute;todos de primer nivel nos condujo a la introducci&oacute;n en nuestro medio de elementos como las siliconas para protecci&oacute;n edilicia, pinturas acr&iacute;licas para fachadas o las pinturas lideres a nivel mundial para el &aacute;rea industrial, que permiti&oacute; que los fabricantes de las mismas contaran con una empresa seria y responsable para otorgar garant&iacute;as mancomunadas, cosa sin precedentes a nivel nacional</p>
<p>En el aislamiento t&eacute;rmico y humidico tambi&eacute;n dijimos presente si bien no fuimos los primeros si fuimos quienes a trav&eacute;s de equipamiento y producto dimos la expansi&oacute;n y generamos el mercado de lo que es hoy el poliuretano expandido.</p>
<p>Es as&iacute; en un constante buscar y encontrar, invertir y arriesgar, aprender y ense&ntilde;ar, que nuestra empresa se mantiene l&iacute;der en el mercado luego de 45 a&ntilde;os de interrumpida trayectoria.</p>';
/* End of file historia_lang.php */