<?php  if (!defined('BASEPATH')) exit('No direct script access allowed');
$lang['certificacion_titulo']='Certificación';
$lang['certificacion_sub_titulo']='Sistemas de la calidad y mejora continua en nuestra organización.';
$lang['certificacion_columna_izquierda']='<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce vel nulla dui, at venenatis lorem. Praesent elementum hendrerit nunc, eget fringilla eros tempor sed. Sed non velit posuere nisl euismod congue. Aenean eget tempus urna. Vivamus nisl sem, molestie at mattis venenatis, fermentum sit amet lectus. Nunc iaculis, quam vestibulum varius elementum, dui lectus aliquet tellus, a tempor nulla diam vel ligula. Vivamus nec laoreet libero. Phasellus sit amet mi in sapien ultricies placerat. Suspendisse non eros enim, vel porta eros. Duis non commodo lectus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec bibendum velit sit amet risus egestas iaculis. Mauris id sem id lorem aliquet iaculis.</p>
            <p>Nullam quis nisi vitae purus dictum mollis. Curabitur ut viverra dui. Donec velit nisl, viverra vel venenatis in, pulvinar at enim. Integer ac nunc magna. Suspendisse potenti. Ut non mi eu ante fermentum vulputate. In sed lobortis lorem. Mauris id mauris nec risus auctor suscipit sit amet ac dolor. Quisque lacus quam, ullamcorper eu sagittis a, dignissim eget erat. Cras lacus nisl, tristique sit amet aliquam id, tempor vitae erat. Ut est elit, pellentesque et tristique vitae, aliquam ac ligula. Pellentesque a ipsum sit amet erat feugiat porta.</p>
            <img src="/assets/images/cert1.jpg" />';
$lang['certificacion_columna_centro']='<img src="/assets/images/cert2.jpg" style="margin-top:15px" />
            <p>Nam a metus orci, in laoreet lacus. Maecenas scelerisque, velit eu sagittis semper, tellus erat faucibus sem, vel faucibus risus risus non quam. Aliquam erat volutpat. Aenean egestas orci vitae lectus viverra a porttitor dui volutpat. Duis sapien lorem, euismod a lobortis vel, semper id nibh. Donec blandit mattis ligula, vel accumsan orci gravida iaculis. Vivamus orci quam, venenatis at mollis congue, consectetur nec nunc. Pellentesque dui enim, mollis a scelerisque et, tempor eget nunc. Quisque aliquam auctor ligula non commodo.</p>
            <p>Phasellus dictum arcu in eros tincidunt elementum. Morbi hendrerit tristique mi. Ut faucibus varius elit eget fermentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed vel commodo enim. Vestibulum congue adipiscing eros a aliquam. Suspendisse sit amet nibh egestas orci molestie viverra et eget felis. Phasellus et dolor ac nisi consequat ullamcorper. Phasellus posuere urna et libero varius vitae elementum justo vehicula. Etiam accumsan euismod purus, sed tempor odio laoreet at.</p>
            <p>Praesent consectetur ultrices tellus, sed lobortis purus eleifend nec. Cras quis mi mi. Morbi sed iaculis sapien. Nam feugiat libero lacinia nibh faucibus quis sodales mi pellentesque. </p>';
$lang['certificacion_columna_derecha']='<p>In hac habitasse platea dictumst. Phasellus urna augue, semper blandit egestas sit amet, tincidunt faucibus justo. Phasellus ornare aliquam ipsum ut tristique. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi a lorem quis dolor placerat ornare non vel est. Etiam purus tortor, accumsan sit amet consequat id, egestas ut libero. Aenean pharetra pharetra lacus, sit amet vestibulum velit suscipit nec.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce vel nulla dui, at venenatis lorem. Praesent elementum hendrerit nunc, eget fringilla eros tempor sed. Sed non velit posuere nisl euismod congue. Aenean eget tempus urna. Vivamus nisl sem, molestie at mattis venenatis, fermentum sit amet lectus. Nunc iaculis, quam vestibulum varius elementum, dui lectus aliquet tellus, a tempor nulla diam vel ligula. Vivamus nec laoreet libero. Phasellus sit amet mi in sapien ultricies placerat. Suspendisse non eros enim, vel porta eros. Duis non commodo lectus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec bibendum velit sit amet risus egestas iaculis. Mauris id sem id lorem aliquet iaculis.</p>
            <img src="/assets/images/cert3.jpg" />';
