<?php  if (!defined('BASEPATH')) exit('No direct script access allowed');
$lang['historia_campeones_titulo']='Campeones historicos';
$lang['historia_campeones_sub_titulo']='Campeones listado por periodo';
$lang['historia_campeones_imagen']='Imagen';
$lang['historia_campeones_nombre']='Nombre';
$lang['historia_campeones_periodo']='Periodo';
$lang['historia_deportistas_titulo']='Deportistas del a&ntilde;o historicos';
$lang['historia_deportistas_sub_titulo']='Deportistas del a&ntilde;o listado por periodo';
$lang['historia_deportistas_imagen']='Imagen';
$lang['historia_deportistas_nombre']='Nombre';
$lang['historia_deportistas_periodo']='Periodo';
$lang['historia_presidentes_titulo']='Presidentes historicos';
$lang['historia_presidentes_sub_titulo']='Presidentes listado por periodo';
$lang['historia_presidentes_imagen']='Imagen';
$lang['historia_presidentes_nombre']='Nombre';
$lang['historia_presidentes_periodo']='Periodo';
$lang['historia_raid_titulo']='Historia del Raid';
$lang['historia_raid_contenido']='<h3>Concepto del Raid</h3>
<p>Entiendase por raid...</p>
<h3>&iquest;Que es el Raid?</h3>
<p>El <strong>enduro ecuestre</strong>, <strong>endurance</strong> o <strong>raid</strong> (denominaci&oacute;n esta &uacute;ltima usual en <a title="España" href="http://es.wikipedia.org/wiki/España">Espa&ntilde;a</a>) es un <a title="Deportes ecuestres" href="http://es.wikipedia.org/wiki/Deportes_ecuestres">deporte ecuestre</a> en el cual se pone a prueba la velocidad, habilidad y la resistencia f&iacute;sica y psicol&oacute;gica de <a class="mw-redirect" title="Caballo" href="http://es.wikipedia.org/wiki/Caballo">caballo</a> y <a title="Jinete" href="http://es.wikipedia.org/wiki/Jinete">jinete</a>, ya que ambos deben recorrer grandes distancias en un d&iacute;a, a trav&eacute;s de los m&aacute;s diversos terrenos y contra el tiempo.<sup id="cite_ref-1" class="reference"><a href="http://es.wikipedia.org/wiki/Enduro_ecuestre#cite_note-1">1</a></sup> Para lo anterior el jinete debe tener la capacidad de dosificar el  esfuerzo de su caballo y llevar un ritmo adecuado durante la prueba. Al  finalizar una carrera se le toman las pulsaciones al caballo y, si est&aacute;n  por encima de lo permitido, el jinete es eliminado.<sup id="cite_ref-2" class="reference"><a href="http://es.wikipedia.org/wiki/Enduro_ecuestre#cite_note-2">2</a></sup></p>
<p>La competencia consiste en completar un n&uacute;mero determinado de etapas o  fases con una cantidad de kil&oacute;metros preestablecidos. El recorrido es  muy variado, con varios tipos de suelo y obst&aacute;culos naturales, y al  final de cada fase los caballos son inspeccionados por veterinarios,  quienes, de no mediar ning&uacute;n problema m&eacute;dico, dar&aacute;n la autorizaci&oacute;n para  continuar en carrera. Para campeonatos mundiales la distancia a  recorrer es de 160 kil&oacute;metros, divididos en seis fases, que es  completada por los competidores en 12 o m&aacute;s horas.</p>
<p>Las categor&iacute;as en competencia son: 20 km, 40 km, 60 km, 80 km, 120  km, 130 km y 160 km. Las categor&iacute;as se determinan con relaci&oacute;n a 5  factores: entrenamiento, esfuerzo, distancia, preparaci&oacute;n f&iacute;sica tanto  del caballo como del jinete y experiencia en carrera.</p>
<p>Fuente <a href="http://es.wikipedia.org/wiki/Enduro_ecuestre">http://es.wikipedia.org/wiki/Enduro_ecuestre</a></p>';
$lang['historia_feu_titulo']='Historia del FEU';
$lang['historia_feu_contenido']='<h3>Historia de la FEU</h3>
<p>Historia del Raid Uruguayo</p>
<span>Desde Uruguay, los amigos del Endurance de ese gran Pa&iacute;s, donde la Resistencia Ecuestre</span> <span>es  una pasi&oacute;n, me remiten este articulo sobre la historia del raid  Uruguayo, lo que no se conoce no se ama, y la historia hay que conocerla  para tenerla en cuenta y guardar un respeto a los que nos antecedieron  en esta bonita afici&oacute;n h&iacute;pica.</span> <span>Esta es la historia escrita por Eduardo Lerena en Raidistas.com:</span>
<h2 class="art-postheader"><a href="http://www.raidistas.com/index.php/contenidos/la-columna/eduardo-lerena/113-jinetes-y-amazonas-de-nuestro-raid">"Jinetes y Amazonas de nuestro raid</a></h2>
<div class="art-postheadericons art-metadata-icons"><span><strong><span class="art-postauthoricon">Escrito por Eduardo Lerena</span> . </strong></span></div>
<div><span><strong>Hace  100 a&ntilde;os, 13 de octubre de 1913, se disputo la primera marcha de  resistencia ecuestre Sarand&iacute; Grande &ndash; Florida - Sarand&iacute; Grande, motivo  m&aacute;s que suficiente para recordar a los &uacute;nicos dos jinetes, de los trece  que participaron, que completaron el recorrido, llenos de impericia y  desconocimiento.</strong></span></div>
<div><span><strong>El ganador de la competencia fue Amadeo Rodr&iacute;guez, y el segundo lugar lo ocup&oacute; Eduardo Grajales.</strong></span></div>
<div><span><strong>Transcurrieron dos a&ntilde;os para que,  acalladas las duras cr&iacute;ticas por el desmedido&nbsp; esfuerzo exigido a las  cabalgaduras, se disputara la segunda prueba, esta vez hacia la ciudad  de Durazno, resultando ganador Coralio Bentancour.</strong></span></div>
<div class="separator"><span><strong>Es imposible nombrar a los miles de jinetes que han participado desde  1935 a la fecha, pero del mismo modo en que lo hicimos en &ldquo;Grandes  caballos de la historia&rdquo;, sentimos la obligaci&oacute;n y el deber de nombrar a  quien, en pol&eacute;mico final, fuera el ganador del 1&ordf; Raid H&iacute;pico de la era  moderna, el decano &ldquo;Batalla de Sarand&iacute;&rdquo;, Don Eladio Gonz&aacute;lez C&eacute;spedes,  que le gano por un cuerpo al eximio jinete Alcides Cassani, el recordado  &ldquo;Sapo&rdquo;, al cual tuvimos la inmensa dicha de ver correr el &ldquo;33  Orientales&rdquo;, siendo esa su &uacute;ltima participaci&oacute;n, y en la que defendi&oacute; un  puesto lejano con uno de sus mejores alumnos, Enrique Arroqui &ldquo;El  Chueco&rdquo;.</strong></span></div>
<span>&nbsp;</span><br />
<div><span><strong>&nbsp;<strong><img src="http://www.raidistas.com/images/Noticias/_Agosto/1.gif" border="0" alt="" /></strong></strong></span></div>
<div><span><strong>Surgen muchos recuerdos, todos afloran  al galope largo y tendido, todos piden permiso para estar. Soy  consciente de que ser&aacute; muy dif&iacute;cil nombrarlos a todos, pero trataremos,  en lo posible, d&eacute;cada a d&eacute;cada, recordarlos.</strong></span></div>
<div><span><strong>&ldquo;El Sapo&rdquo; Cassani pose&iacute;a la virtud  innata de hacer andar a los caballos distendidos, aprovech&aacute;ndolos al  m&aacute;ximo, sin pedirles todo, les hac&iacute;a dar todo&hellip; En los de trote fue un  artista y en los &ldquo;largos&rdquo; se luci&oacute; siempre, aunque nunca pudo ganar un  &ldquo;Batalla de Sarand&iacute;&rdquo;, las cosas raras del destino&hellip;</strong></span></div>
<div><span><strong>Don Ar&iacute;stides Scaron Pallares se dio el  gran gusto de participar en la &ldquo;Copa de Oro&rdquo; del decano, en 1984. En  aquel momento la curiosidad me invadi&oacute; y un buen trayecto en el camino  vecinal de Piedras Coloradas me deleite mir&aacute;ndolo. Hoy, a casi 29 a&ntilde;os,  sigo pensando y cada vez me convenzo m&aacute;s, que tanto &ldquo;El Sapo&rdquo; Cassani  como &ldquo;El Chivo&rdquo; Scaron fueron adelantados en su &eacute;poca, hoy est&aacute;n  vigentes en cada uno de los jinetes de raid, lo que ellos hac&iacute;an es lo  que hoy hacen muchos jinetes que practican este deporte ecuestre, desde  la forma de sentarse para aliviar el lomo, administrar las energ&iacute;as para  completar el recorrido promediando la velocidad sin desperdiciar  tiempo. Hoy los adelantos tecnol&oacute;gicos son muchos, monturas de fibra de  carbono, jergas sint&eacute;ticas, estribos de aluminio, bombas el&eacute;ctricas para  mojar, apoyo constante desde las unidades acompa&ntilde;antes, pistas elegidas  para el mejor desempe&ntilde;o, en fin, totalmente diferente en estos  aspectos, pero encima de los caballos las mismas cosas.</strong></span></div>
<div><span><strong>En la d&eacute;cada del &rsquo;40 apareci&oacute; la  diminuta dama de la boina roja, Isabel Placeres, &ldquo;&iquest;Una mujer mezcl&aacute;ndose  con hombres corriendo raid de caballos?&rdquo;, se preguntaban todos, y  criticaban, en aquella &eacute;poca. Sin embargo en el 11&ordm; &ldquo;Batalla de  Sarand&iacute;&rdquo;, (1945) clasific&oacute; 2&ordf; con &ldquo;Firulete&rdquo; detr&aacute;s del Tte. Eduardo  Elduayen, quien hab&iacute;a sido ganador en 1949 de la primera edici&oacute;n del &ldquo;33  Orientales&rdquo; del Club Deportivo Social &ldquo;Sarand&iacute;&rdquo;, de Sarand&iacute; Grande.</strong></span></div>
<div class="separator"><strong><img src="http://www.raidistas.com/images/Noticias/_Agosto/5.gif" border="0" alt="" /></strong></div>
<span>&nbsp;</span><br />
<div><span><strong>&nbsp;Isabel Placeres era hija de un  entrenador de caballos pura sangre en Las Piedras, as&iacute; naci&oacute; su pasi&oacute;n  por los caballos y su gran estilo para montarlos. A m&aacute;s de un pupilo del  stud paterno le hizo alguna &ldquo;partida&rdquo;,&nbsp; prepar&aacute;ndolos para alguna  carrera.</strong></span></div>
<div><span><strong>Como dama, le otorgaban 5 kg&nbsp; de  ventaja. Hasta que en 1947 en un final electrizante, &ldquo;sin luz&rdquo; le gan&oacute;  al Tte. Vel&aacute;zquez Scardino. Tras este desenlace se terminaron las  ventajas.</strong></span></div>
<div><span><strong>En 1950 fue&nbsp; segunda, detr&aacute;s del Tte.  Luis Guarino. En 1951 repiti&oacute; el triunfo con &ldquo;Ponciano&rdquo; y logr&oacute; tambi&eacute;n  el primer lugar en 1952, siendo este su &uacute;ltimo triunfo en Sarand&iacute;  Grande.</strong></span></div>
<div><span><strong>La mayor&iacute;a de los participantes eran  militares provenientes de la Escuela de Equitaci&oacute;n del Ejercito, con sus  caracter&iacute;sticos uniformes, sentados en las monturas con elegancia  admirable, siendo el primer oficial que gan&oacute; un &ldquo;Batalla de Sarand&iacute;&rdquo; el  Tte. Ra&uacute;l Fern&aacute;ndez Monteavaro, en 1940.</strong></span></div>
<div><span><strong>Continuaron participando en cada una de  las existentes, en las dos de Sarand&iacute; Grande y en Santa Clara de Olimar,  pagos del primer jinete campe&oacute;n nacional, Washington &ldquo;Nanico&rdquo;&nbsp; Saravia,  que a pesar de la falta de su brazo derecho, ha sido uno de los  mejores&nbsp; de todas las &eacute;pocas.</strong></span></div>
<div><span><strong>Justamente en un &ldquo;Independencia  Nacional&rdquo; (1967) donde ya hab&iacute;a ganado dos veces consecutivas con  &ldquo;Cuerito&rdquo; (1965 y 1966), el Tte. Jes&uacute;s Monge con &ldquo;Yo-Yo&rdquo;, le gan&oacute; el  lado de subir al entrar a la recta, y no lo dej&oacute; utilizar el l&aacute;tigo. Sin  dudarlo, dos grandes jinetes de la rica historia de la Federaci&oacute;n  Ecuestre Uruguaya.</strong></span></div>
<div class="separator"><strong><img src="http://www.raidistas.com/images/Noticias/_Agosto/4.gif" border="0" alt="" /></strong></div>
<span>&nbsp;</span><br />
<div><span><strong>&nbsp;Como cat&oacute;lico, agradezco a Dios, la  oportunidad de haber sido testigo del encuentro, luego de varios a&ntilde;os,  de otros dos inmensos jinetes y rivales ac&eacute;rrimos en la carretera, y  amigos, bien amigos fuera de ellas: Ataulfo Caetano y Ra&uacute;l Acosta. Fue  precisamente en v&iacute;speras de la Copa de Oro del &ldquo;Independencia Nacional&rdquo;,  en el Club Hispano Uruguayo de Santa Clara de Olimar, en agosto de  2001. Est&aacute;bamos conversando junto a Ra&uacute;l Acosta, recordando y  escuch&aacute;ndolo muy atentamente. De pronto me pregunt&oacute; &ldquo;&iquest;No sabes si  Ataulfo anda por ac&aacute;?&rdquo;. Y es por esto que agradezco infinitamente: mir&eacute;  hacia mi derecha, y cigarrillo en mano, mirando a lo lejos con su &ldquo;Don  Fernando&rdquo; ingres&oacute; al Hispano la figura inconfundible del hombre de Paso  Pereira; Ataulfo. Inmediatamente lo llame, y sin mediar palabras, se  confundieron en un largo y apretado abrazo, como descarg&aacute;ndose, o  traspas&aacute;ndose las ansias de uno al otro. Aquella eterna rivalidad  carretera estaba ya muy lejana.</strong></span></div>
<div><span><strong>&nbsp;<span><strong><img src="http://www.raidistas.com/images/Noticias/_Agosto/2.gif" border="0" alt="" /></strong></span></strong></span></div>
<div><span><strong>Entre tantas y tantas cosas que  recordaron -yo todo o&iacute;dos, como no pod&iacute;a ser de otra manera-, me  compartieron una de las an&eacute;cdotas m&aacute;s bellas que he escuchado de la boca  de verdaderos caballeros &ndash; y reitero, grandes rivales- pero hombres de  bien en todos los sentidos.</strong></span></div>
<div><span><strong>La historia que les escuch&eacute; hablaba de  &ldquo;un &lsquo;Libertad&rsquo;, en Cerro Chato&rdquo;, en el cual Ataulfo hab&iacute;a ganado con un  caballo de Orosman Bengoechea y Ra&uacute;l hab&iacute;a sido tercero. En la noche del  domingo le avisaron a Ataulfo que hab&iacute;a fallecido su mam&aacute;. Los  dirigentes del Hispano le preguntaron qui&eacute;n iba a hacer la prueba de  suficiencia, y sin dudar un instante les dijo: &ldquo;Ra&uacute;l Acosta&rdquo;.  Sorprendidos y dudosos, le preguntaron: &ldquo;&iquest;Est&aacute; seguro Ataulfo?&rdquo;.</strong></span></div>
<div><span><strong>El fenomenal Ra&uacute;l Acosta se  responsabiliz&oacute; de montar el caballo de su entra&ntilde;able amigo, y el lunes  realiz&oacute; la prueba reglamentariamente. Demostraci&oacute;n cabal de  caballerosidad y de gran respeto, si las hay.</strong></span></div>
<div><span><strong>En un momento de ese reencuentro,  Ataulfo le pregunto a Ra&uacute;l: &ldquo;Para vos &iquest;cu&aacute;l fue el mejor jinete de  raid?&rdquo;. Y los dos coincidieron: &ldquo;Mondego grande&rdquo;. Se refer&iacute;an a Rodolfo  &ldquo;Calucho&rdquo; Mondego, que luci&oacute; su esbelta estampa en hip&oacute;dromos, pistas, y  tambi&eacute;n en las carreteras. Un verdadero fen&oacute;meno encima de los equinos.<br /></strong></span></div>
<p>Contenido sacado de <a href="http://ggjineteraid.blogspot.com/2013/09/historia-del-raid-uruguayo.html">http://ggjineteraid.blogspot.com/2013/09/historia-del-raid-uruguayo.html</a></p>';
/* End of file historia_lang.php */